// <auto-generated />
using BookManagerFinal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookManagerFinal.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20241121141037_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BookManagerFinal.Models.BookModel", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Summary = "young adult",
                            Genre = "young adult",
                            Name = "Song of Achilles",
                            Rating = 5,
                            Status = "read"
                        },
                        new
                        {
                            BookId = 2,
                            Summary = "fantasy",
                            Genre = "fantasy",
                            Name = "Harry Potter and the Prisoner of Azkaban",
                            Rating = 5,
                            Status = "read"
                        },
                        new
                        {
                            BookId = 3,
                            Summary = "young adult",
                            Genre = "young adult",
                            Name = "I'll Give You the Sun",
                            Rating = 4,
                            Status = "will read"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
